//#include ""
#pragma once
#include <iostream>
#include <cstdio>
#include <stack>
#include <string>
#include <vector>
#include "omp.h"
#include <sstream>
#include <time.h>
#include <GL/glew.h>
#include <GL/glut.h>
#include "FreeImage.h"
#include "shaders.h"
#include "Shapes.h"
#include "Intersection.h"
#include "Light.h"
#include "Scene.h"
#include "Ray.h"
#include "Scene.h"
#include "Transform.h"
#include "util\vec3.hpp"
#include "util\aabb.hpp"
#include "util\rtmath.hpp"
#include "SceneAccel\bvh.hpp"
#include "Material.h"
#include "glmHeader.h"

